/**
 * รายการอุปกรณ์ Master 40 รายการประจำรถพยาบาล
 * หน่วยกู้ชีพเทศบาลเมืองพันท้ายนรสิงห์
 * 
 * คุณสมบัติสำคัญ:
 * - isMandatory: ต้องตรวจด้วยตนเองเสมอ
 * - isQuantitative: ต้องกรอกตัวเลขจริงหรือตัวเลือกปริมาณ
 * - allowBulkReady: อนุญาตให้ปุ่ม Bulk Ready เปลี่ยนสถานะได้หรือไม่ (น้ำกลั่น, O2, น้ำมัน, DTX, ไม้ดาม = false)
 */
export const DEFAULT_EQUIPMENT_MASTER = [
  {
    id: 'eq-01',
    equipment_no: 1,
    equipment_name: 'สัญญาณไฟฉุกเฉิน',
    category: 'ยานพาหนะและความปลอดภัย',
    category_code: 'VEHICLE',
    minimum_quantity: 1,
    unit: 'ชุด',
    requirement: 'ไฟไซเรนและเสียงเตือนทำงานปกติ',
    is_mandatory: false,
    is_quantitative: false,
    allow_bulk_ready: true,
    check_type: 'NORMAL'
  },
  {
    id: 'eq-02',
    equipment_no: 2,
    equipment_name: 'ไฟส่องสว่าง/เลี้ยวซ้ายขวา',
    category: 'ยานพาหนะและความปลอดภัย',
    category_code: 'VEHICLE',
    minimum_quantity: 1,
    unit: 'ระบบ',
    requirement: 'ไฟหน้า ไฟท้าย ไฟเลี้ยว ไฟเบรก ติดครบ',
    is_mandatory: false,
    is_quantitative: false,
    allow_bulk_ready: true,
    check_type: 'NORMAL'
  },
  {
    id: 'eq-03',
    equipment_no: 3,
    equipment_name: 'ไฟฉาย',
    category: 'ยานพาหนะและความปลอดภัย',
    category_code: 'VEHICLE',
    minimum_quantity: 1,
    unit: 'กระบอก',
    requirement: 'แบตเตอรี่พร้อมใช้งาน สว่างชัดเจน',
    is_mandatory: false,
    is_quantitative: false,
    allow_bulk_ready: true,
    check_type: 'NORMAL'
  },
  {
    id: 'eq-04',
    equipment_no: 4,
    equipment_name: 'ลมยาง',
    category: 'ยานพาหนะและความปลอดภัย',
    category_code: 'VEHICLE',
    minimum_quantity: 4,
    unit: 'ล้อ',
    requirement: 'แรงดันลมยางเหมาะสมทั้ง 4 ล้อ',
    is_mandatory: false,
    is_quantitative: false,
    allow_bulk_ready: true,
    check_type: 'NORMAL'
  },
  {
    id: 'eq-05',
    equipment_no: 5,
    equipment_name: 'น้ำกลั่น',
    category: 'ยานพาหนะและความปลอดภัย',
    category_code: 'VEHICLE',
    minimum_quantity: 1,
    unit: 'หม้อ/ขวด',
    requirement: 'ตรวจทุกวัน (ห้าม Auto Ready)',
    is_mandatory: true,
    is_quantitative: false,
    allow_bulk_ready: false, // กฎสำคัญ: ห้าม Auto Ready
    check_type: 'MANDATORY_WATER',
    reason_options: [
      'น้ำกลั่นหมด',
      'น้ำกลั่นไม่เพียงพอ',
      'ต้องเติมน้ำกลั่น',
      'ภาชนะชำรุด',
      'อื่นๆ'
    ]
  },
  {
    id: 'eq-06',
    equipment_no: 6,
    equipment_name: 'น้ำมันเชื้อเพลิง',
    category: 'ยานพาหนะและความปลอดภัย',
    category_code: 'VEHICLE',
    minimum_quantity: 1,
    unit: 'ถัง',
    requirement: 'ไม่ต่ำกว่า 1/2 ถัง',
    is_mandatory: true,
    is_quantitative: true,
    allow_bulk_ready: false,
    check_type: 'FUEL_LEVEL',
    fuel_options: [
      { label: 'มากกว่า 1/2 ถัง', value: 'MORE_THAN_HALF', is_ready: true },
      { label: 'เท่ากับ 1/2 ถัง', value: 'EQUAL_HALF', is_ready: true },
      { label: 'ต่ำกว่า 1/2 ถัง', value: 'LESS_THAN_HALF', is_ready: false }
    ]
  },
  {
    id: 'eq-07',
    equipment_no: 7,
    equipment_name: 'ทูนิเก้ (Tourniquet)',
    category: 'การห้ามเลือดและปฐมพยาบาล',
    category_code: 'FIRST_AID',
    minimum_quantity: 1,
    unit: 'เส้น',
    requirement: 'สภาพสมบูรณ์ พร้อมใช้งาน',
    is_mandatory: false,
    is_quantitative: false,
    allow_bulk_ready: true,
    check_type: 'NORMAL'
  },
  {
    id: 'eq-08',
    equipment_no: 8,
    equipment_name: 'เสื้อสะท้อนแสง',
    category: 'ความปลอดภัยเจ้าหน้าที่',
    category_code: 'SAFETY',
    minimum_quantity: 2,
    unit: 'ตัว',
    requirement: 'สภาพสมบูรณ์ พร้อมใช้งาน',
    is_mandatory: false,
    is_quantitative: false,
    allow_bulk_ready: true,
    check_type: 'NORMAL'
  },
  {
    id: 'eq-09',
    equipment_no: 9,
    equipment_name: 'รองเท้าบูธ',
    category: 'ความปลอดภัยเจ้าหน้าที่',
    category_code: 'SAFETY',
    minimum_quantity: 2,
    unit: 'คู่',
    requirement: '2 คู่',
    is_mandatory: false,
    is_quantitative: true,
    allow_bulk_ready: false,
    check_type: 'MINIMUM_QUANTITY'
  },
  {
    id: 'eq-10',
    equipment_no: 10,
    equipment_name: 'ระบบแอร์',
    category: 'ยานพาหนะและความปลอดภัย',
    category_code: 'VEHICLE',
    minimum_quantity: 1,
    unit: 'ระบบ',
    requirement: 'เย็นปกติ ทั้งหน้าและห้องพยาบาล',
    is_mandatory: false,
    is_quantitative: false,
    allow_bulk_ready: true,
    check_type: 'NORMAL'
  },
  {
    id: 'eq-11',
    equipment_no: 11,
    equipment_name: 'กระเป๋าพยาบาลพร้อมอุปกรณ์',
    category: 'การปฐมพยาบาล',
    category_code: 'FIRST_AID',
    minimum_quantity: 1,
    unit: 'ใบ',
    requirement: 'พอใช้',
    is_mandatory: false,
    is_quantitative: false,
    allow_bulk_ready: true,
    check_type: 'ADEQUATE_CHECK'
  },
  {
    id: 'eq-12',
    equipment_no: 12,
    equipment_name: 'Hard Collar',
    category: 'การดามและเคลื่อนย้าย',
    category_code: 'IMMOBILIZATION',
    minimum_quantity: 3,
    unit: 'ชิ้น',
    requirement: '3 ชิ้น',
    is_mandatory: false,
    is_quantitative: true,
    allow_bulk_ready: false,
    check_type: 'MINIMUM_QUANTITY'
  },
  {
    id: 'eq-13',
    equipment_no: 13,
    equipment_name: 'กรรไกร',
    category: 'การปฐมพยาบาล',
    category_code: 'FIRST_AID',
    minimum_quantity: 1,
    unit: 'เล่ม',
    requirement: 'คม ไม่ขึ้นสนิม ใช้งานได้ดี',
    is_mandatory: false,
    is_quantitative: false,
    allow_bulk_ready: true,
    check_type: 'NORMAL'
  },
  {
    id: 'eq-14',
    equipment_no: 14,
    equipment_name: 'ไม้ดามแขน',
    category: 'การดามและเคลื่อนย้าย',
    category_code: 'IMMOBILIZATION',
    minimum_quantity: 4,
    unit: 'อัน',
    requirement: '4 อัน',
    is_mandatory: false,
    is_quantitative: true,
    allow_bulk_ready: false,
    check_type: 'MINIMUM_QUANTITY'
  },
  {
    id: 'eq-15',
    equipment_no: 15,
    equipment_name: 'ไม้ดามขา',
    category: 'การดามและเคลื่อนย้าย',
    category_code: 'IMMOBILIZATION',
    minimum_quantity: 4,
    unit: 'อัน',
    requirement: '4 อัน',
    is_mandatory: false,
    is_quantitative: true,
    allow_bulk_ready: false,
    check_type: 'MINIMUM_QUANTITY'
  },
  {
    id: 'eq-16',
    equipment_no: 16,
    equipment_name: 'เฝือกลม',
    category: 'การดามและเคลื่อนย้าย',
    category_code: 'IMMOBILIZATION',
    minimum_quantity: 1,
    unit: 'ชุด',
    requirement: 'ไม่รั่ว ซึม วาล์วใช้งานได้',
    is_mandatory: false,
    is_quantitative: false,
    allow_bulk_ready: true,
    check_type: 'NORMAL'
  },
  {
    id: 'eq-17',
    equipment_no: 17,
    equipment_name: 'ชุด Spinalboard พร้อมสายรัด',
    category: 'การดามและเคลื่อนย้าย',
    category_code: 'IMMOBILIZATION',
    minimum_quantity: 1,
    unit: 'ชุด',
    requirement: 'บอร์ดไม่แตกหัก สายรัดครบชุด',
    is_mandatory: false,
    is_quantitative: false,
    allow_bulk_ready: true,
    check_type: 'NORMAL'
  },
  {
    id: 'eq-18',
    equipment_no: 18,
    equipment_name: 'Stretcher',
    category: 'การดามและเคลื่อนย้าย',
    category_code: 'IMMOBILIZATION',
    minimum_quantity: 1,
    unit: 'เตียง',
    requirement: 'เข็นและปรับระดับ ล็อคได้มั่นคง',
    is_mandatory: false,
    is_quantitative: false,
    allow_bulk_ready: true,
    check_type: 'NORMAL'
  },
  {
    id: 'eq-19',
    equipment_no: 19,
    equipment_name: 'Stretcher เก้าอี้นั่ง',
    category: 'การดามและเคลื่อนย้าย',
    category_code: 'IMMOBILIZATION',
    minimum_quantity: 1,
    unit: 'ตัว',
    requirement: 'พับกาง ล็อคได้ปกติ',
    is_mandatory: false,
    is_quantitative: false,
    allow_bulk_ready: true,
    check_type: 'NORMAL'
  },
  {
    id: 'eq-20',
    equipment_no: 20,
    equipment_name: 'KED',
    category: 'การดามและเคลื่อนย้าย',
    category_code: 'IMMOBILIZATION',
    minimum_quantity: 1,
    unit: 'ชุด',
    requirement: 'อุปกรณ์ดึงกระดูกสันหลัง ครบชุด',
    is_mandatory: false,
    is_quantitative: false,
    allow_bulk_ready: true,
    check_type: 'NORMAL'
  },
  {
    id: 'eq-21',
    equipment_no: 21,
    equipment_name: 'Cannula ผู้ใหญ่/เด็ก',
    category: 'ระบบทางเดินหายใจ',
    category_code: 'AIRWAY',
    minimum_quantity: 3,
    unit: 'เส้น',
    requirement: '3 เส้น',
    is_mandatory: false,
    is_quantitative: true,
    allow_bulk_ready: false,
    check_type: 'MINIMUM_QUANTITY'
  },
  {
    id: 'eq-22',
    equipment_no: 22,
    equipment_name: 'Mask with bag / ผู้ใหญ่',
    category: 'ระบบทางเดินหายใจ',
    category_code: 'AIRWAY',
    minimum_quantity: 3,
    unit: 'ชุด',
    requirement: '3 ชุด',
    is_mandatory: false,
    is_quantitative: true,
    allow_bulk_ready: false,
    check_type: 'MINIMUM_QUANTITY'
  },
  {
    id: 'eq-23',
    equipment_no: 23,
    equipment_name: 'Mask with bag / เด็ก',
    category: 'ระบบทางเดินหายใจ',
    category_code: 'AIRWAY',
    minimum_quantity: 3,
    unit: 'ชุด',
    requirement: '3 ชุด',
    is_mandatory: false,
    is_quantitative: true,
    allow_bulk_ready: false,
    check_type: 'MINIMUM_QUANTITY'
  },
  {
    id: 'eq-24',
    equipment_no: 24,
    equipment_name: 'เครื่องกระตุ้นหัวใจ/สายสัญญาณ',
    category: 'เครื่องมือประเมินและช่วยชีวิต',
    category_code: 'DIAGNOSTIC',
    minimum_quantity: 1,
    unit: 'เครื่อง',
    requirement: 'AED/Defib แบตเตอรี่พร้อม สายครบ',
    is_mandatory: false,
    is_quantitative: false,
    allow_bulk_ready: true,
    check_type: 'NORMAL'
  },
  {
    id: 'eq-25',
    equipment_no: 25,
    equipment_name: 'Ambu Bag',
    category: 'ระบบทางเดินหายใจ',
    category_code: 'AIRWAY',
    minimum_quantity: 1,
    unit: 'ชุด',
    requirement: 'พอใช้',
    is_mandatory: false,
    is_quantitative: false,
    allow_bulk_ready: true,
    check_type: 'ADEQUATE_CHECK'
  },
  {
    id: 'eq-26',
    equipment_no: 26,
    equipment_name: 'Oral Airway เล็ก',
    category: 'ระบบทางเดินหายใจ',
    category_code: 'AIRWAY',
    minimum_quantity: 1,
    unit: 'ชิ้น',
    requirement: 'สะอาด บรรจุซองพร้อมใช้',
    is_mandatory: false,
    is_quantitative: false,
    allow_bulk_ready: true,
    check_type: 'NORMAL'
  },
  {
    id: 'eq-27',
    equipment_no: 27,
    equipment_name: 'Oral Airway กลาง',
    category: 'ระบบทางเดินหายใจ',
    category_code: 'AIRWAY',
    minimum_quantity: 1,
    unit: 'ชิ้น',
    requirement: 'สะอาด บรรจุซองพร้อมใช้',
    is_mandatory: false,
    is_quantitative: false,
    allow_bulk_ready: true,
    check_type: 'NORMAL'
  },
  {
    id: 'eq-28',
    equipment_no: 28,
    equipment_name: 'Oral Airway ใหญ่',
    category: 'ระบบทางเดินหายใจ',
    category_code: 'AIRWAY',
    minimum_quantity: 1,
    unit: 'ชิ้น',
    requirement: 'สะอาด บรรจุซองพร้อมใช้',
    is_mandatory: false,
    is_quantitative: false,
    allow_bulk_ready: true,
    check_type: 'NORMAL'
  },
  {
    id: 'eq-29',
    equipment_no: 29,
    equipment_name: 'เครื่อง Suction Mobile',
    category: 'ระบบทางเดินหายใจ',
    category_code: 'AIRWAY',
    minimum_quantity: 1,
    unit: 'เครื่อง',
    requirement: 'แรงดูดปกติ แบตเตอรี่เต็ม',
    is_mandatory: false,
    is_quantitative: false,
    allow_bulk_ready: true,
    check_type: 'NORMAL'
  },
  {
    id: 'eq-30',
    equipment_no: 30,
    equipment_name: 'เครื่องวัด BP ติดรถยนต์',
    category: 'เครื่องมือประเมินและช่วยชีวิต',
    category_code: 'DIAGNOSTIC',
    minimum_quantity: 1,
    unit: 'เครื่อง',
    requirement: 'คัฟฟ์และเกจ์วัดแม่นยำ',
    is_mandatory: false,
    is_quantitative: false,
    allow_bulk_ready: true,
    check_type: 'NORMAL'
  },
  {
    id: 'eq-31',
    equipment_no: 31,
    equipment_name: 'เครื่องวัด BP Digital',
    category: 'เครื่องมือประเมินและช่วยชีวิต',
    category_code: 'DIAGNOSTIC',
    minimum_quantity: 1,
    unit: 'เครื่อง',
    requirement: 'แบตเตอรี่พร้อม แสดงผลแม่นยำ',
    is_mandatory: false,
    is_quantitative: false,
    allow_bulk_ready: true,
    check_type: 'NORMAL'
  },
  {
    id: 'eq-32',
    equipment_no: 32,
    equipment_name: 'เครื่องวัดออกซิเจน Sat Mobile',
    category: 'เครื่องมือประเมินและช่วยชีวิต',
    category_code: 'DIAGNOSTIC',
    minimum_quantity: 1,
    unit: 'เครื่อง',
    requirement: 'โพรบวัดปกติ ค่าแม่นยำ',
    is_mandatory: false,
    is_quantitative: false,
    allow_bulk_ready: true,
    check_type: 'NORMAL'
  },
  {
    id: 'eq-33',
    equipment_no: 33,
    equipment_name: 'สาย Suction',
    category: 'ระบบทางเดินหายใจ',
    category_code: 'AIRWAY',
    minimum_quantity: 1,
    unit: 'ชุด',
    requirement: 'พอใช้',
    is_mandatory: false,
    is_quantitative: false,
    allow_bulk_ready: true,
    check_type: 'ADEQUATE_CHECK'
  },
  {
    id: 'eq-34',
    equipment_no: 34,
    equipment_name: 'ถุงมือ Dispose',
    category: 'ความปลอดภัยเจ้าหน้าที่',
    category_code: 'SAFETY',
    minimum_quantity: 1,
    unit: 'กล่อง',
    requirement: 'พอใช้',
    is_mandatory: false,
    is_quantitative: false,
    allow_bulk_ready: true,
    check_type: 'ADEQUATE_CHECK'
  },
  {
    id: 'eq-35',
    equipment_no: 35,
    equipment_name: 'เครื่องเจาะ DTX',
    category: 'เครื่องมือประเมินและช่วยชีวิต',
    category_code: 'DIAGNOSTIC',
    minimum_quantity: 1,
    unit: 'เครื่อง',
    requirement: '1 เครื่อง พร้อมแถบตรวจและเข็ม',
    is_mandatory: false,
    is_quantitative: true,
    allow_bulk_ready: false,
    check_type: 'MINIMUM_QUANTITY'
  },
  {
    id: 'eq-36',
    equipment_no: 36,
    equipment_name: 'ออกซิเจน No.1',
    category: 'ระบบออกซิเจนการแพทย์',
    category_code: 'OXYGEN',
    minimum_quantity: 500,
    unit: 'psi',
    requirement: 'ไม่ต่ำกว่า 500 psi (กรอกค่าจริง)',
    is_mandatory: true,
    is_quantitative: true,
    allow_bulk_ready: false,
    check_type: 'OXYGEN_PRESSURE'
  },
  {
    id: 'eq-37',
    equipment_no: 37,
    equipment_name: 'ออกซิเจน No.2',
    category: 'ระบบออกซิเจนการแพทย์',
    category_code: 'OXYGEN',
    minimum_quantity: 500,
    unit: 'psi',
    requirement: 'ไม่ต่ำกว่า 500 psi (กรอกค่าจริง)',
    is_mandatory: true,
    is_quantitative: true,
    allow_bulk_ready: false,
    check_type: 'OXYGEN_PRESSURE'
  },
  {
    id: 'eq-38',
    equipment_no: 38,
    equipment_name: 'ออกซิเจน No.3',
    category: 'ระบบออกซิเจนการแพทย์',
    category_code: 'OXYGEN',
    minimum_quantity: 500,
    unit: 'psi',
    requirement: 'ไม่ต่ำกว่า 500 psi (กรอกค่าจริง)',
    is_mandatory: true,
    is_quantitative: true,
    allow_bulk_ready: false,
    check_type: 'OXYGEN_PRESSURE'
  },
  {
    id: 'eq-39',
    equipment_no: 39,
    equipment_name: 'ความสะอาดภายในรถ',
    category: 'สุขอนามัยและความสะอาด',
    category_code: 'CLEANLINESS',
    minimum_quantity: 1,
    unit: 'ห้อง',
    requirement: 'สะอาด ปลอดเชื้อ ปราศจากขยะ',
    is_mandatory: false,
    is_quantitative: false,
    allow_bulk_ready: true,
    check_type: 'CLEANLINESS_CHECK'
  },
  {
    id: 'eq-40',
    equipment_no: 40,
    equipment_name: 'ความสะอาดภายนอกรถ',
    category: 'สุขอนามัยและความสะอาด',
    category_code: 'CLEANLINESS',
    minimum_quantity: 1,
    unit: 'คัน',
    requirement: 'ล้างสะอาด กระจกใส ยางสะอาด',
    is_mandatory: false,
    is_quantitative: false,
    allow_bulk_ready: true,
    check_type: 'CLEANLINESS_CHECK'
  }
];

export const EQUIPMENT_CATEGORIES = [
  { code: 'ALL', label: 'ทั้งหมด (40 รายการ)' },
  { code: 'VEHICLE', label: 'ยานพาหนะและความปลอดภัย' },
  { code: 'FIRST_AID', label: 'การปฐมพยาบาลและห้ามเลือด' },
  { code: 'IMMOBILIZATION', label: 'การดามและเคลื่อนย้าย' },
  { code: 'AIRWAY', label: 'ระบบทางเดินหายใจ' },
  { code: 'OXYGEN', label: 'ระบบออกซิเจนการแพทย์' },
  { code: 'DIAGNOSTIC', label: 'เครื่องมือประเมินและช่วยชีวิต' },
  { code: 'SAFETY', label: 'ความปลอดภัยเจ้าหน้าที่' },
  { code: 'CLEANLINESS', label: 'สุขอนามัยและความสะอาด' }
];
